config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :families do
    resources :family_users, except: :index
    resources :categories, except: :index
    resources :users, only: %i[edit update]
    resources :homeworks do
      resources :user_homeworks, except: %i[index new]
    end
    get 'homeworks/:id/move_to_opened',
      to: 'homeworks#move_to_opened',
      as: :homework_move_to_opened
  end

  resources :user_homeworks, only: :index do
    resources :estimates,
      only: %i[new create],
      controller: :user_homework_estimates
    get 'estimate_consider', to: 'user_homework_estimates#consider'
    post 'estimate_decision', to: 'user_homework_estimates#decision'
    resources :requests,
      only: %i[new create],
      controller: :user_homework_requests
    resources :request_end,
      only: %i[new create],
      controller: :user_homework_request_ends
    resources :request_answer,
      only: %i[new create],
      controller: :user_homework_request_answers
    resources :request_answer_to_end,
      only: %i[new create],
      controller: :user_homework_request_answer_to_ends
  end

  resources :user_homeworks, only: [] do
    resources :ratings, only: %i[create update destroy]
  end

  resources :homeworks, only: [] do
    resources :comments, only: %i[new create] do
      resources :comments, only: :create
    end
  end

  root to: 'families#index'
end

app/models/family.rb
class Family < ApplicationRecord
  acts_as_paranoid

  mount_uploader :logo, FamilyLogoUploader

  belongs_to :owner, class_name: 'User', foreign_key: :owner_id
  has_many :family_users, dependent: :destroy
  has_many :family_users_parents,
    -> { FamilyUser.all_parents },
    class_name: 'FamilyUser'
  has_many :family_users_children,
    -> { FamilyUser.all_children },
    class_name: 'FamilyUser'
  has_many :users, through: :family_users, dependent: :destroy
  has_many :all_parents, through: :family_users_parents, source: :user
  has_many :all_children, through: :family_users_children, source: :user
  has_many :categories, dependent: :destroy
  has_many :homeworks, dependent: :destroy

  validates :name, :owner_id, presence: true

  auto_strip_attributes :name

  def add_parent(user)
    family_users_parents.create(user: user)
  end

  def owner?(user)
    owner_id == user.id
  end

  def parent?(user)
    all_parents.include?(user)
  end

  def member?(user)
    users.include?(user)
  end
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  before_action :set_family, only: %i[show edit update destroy]

  def index
    @families = Family.includes(:family_users).decorate
  end

  def show
    @family_users = @family.family_users.group_by(&:role)
  end

  def new
    @family = Family.new.decorate
    authorize @family
  end

  def create
    @family = Family.new(family_params)
    authorize @family
    @family.owner_id = current_user.id

    if @family.save
      @family.add_parent(current_user)
      redirect_to @family
    else
      render :new
    end
  end

  def update
    if @family.update(family_params)
      redirect_to @family
    else
      render :edit
    end
  end

  def destroy
    @family.destroy
    redirect_to families_path
  end

  private

  def set_family
    @family = Family.find(params[:id]).decorate
    authorize @family
  end

  def family_params
    params.require(:family).permit(:name, :logo)
  end
end

app/views/families/_form.html.haml
= simple_form_for(@family) do |f|
  .form-group
    = family_logo_img(@family)
  .form-group
    = f.file_field :logo
  .form-group
    = f.input :name
  .form-group
    = f.submit

app/views/families/edit.html.haml
.page-header
  %h1= t('.title')

= render 'form'

- if policy(@family).show?
  = link_to t('general.show'), @family
  \|
= link_to t('general.back'), families_path

app/views/families/index.html.haml
.page-header
  %h1= t('.title')

- if @families.blank?
  %p= t('.have_no_families')
- else
  %table.table.table-hover
    %thead
      %tr
        %th= t('.name')
        %th= t('.homeworks')
        %th= t('.memebers_count')
        %th

    %tbody
      - @families.each do |family|
        %tr
          %td
            = family_logo_img(family)
            = family.name
          %td= link_to t('.homeworks'), family_homeworks_path(family)
          %td= family.family_users.count
          %td
            - if policy(family).show?
              = link_to t('general.show'), family
            - if policy(family).edit?
              \|
              = link_to t('general.edit'), edit_family_path(family)
            - if policy(family).destroy?
              \|
              = link_to t('general.destroy'), family,
                method: :delete, 'data-confirm': t('general.confirm')

- if policy(:family).create?
  = link_to t('.new'), new_family_path

app/views/families/new.html.haml
.page-header
  %h1= t('.title')

= render 'form'

= link_to t('general.back'), families_path

app/views/families/show.html.haml
.page-header
  %h1= @family.name

%table.table.table-bordered.table-striped
  %tbody
    %tr
      %td= t('.logo')
      %td= family_logo_img(@family)
    %tr
      %td= t('.memebers_count')
      %td= @family.family_users.count
    %tr
      %td= link_to t('.homeworks_count'), family_homeworks_path(@family)
      %td= @family.homeworks.count

- @family_users.each do |role, family_users|
  %h4= t(".#{role}")
  %table.table.table-hover
    %thead
      %tr
        %th
        %th= t('.completed_homeworks_count')
        %th= t('.completed_homeworks_on_time_count')
        %th= t('.overdue_homeworks_count')
        %th= t('.rating')
        %th
    %tbody
      - family_users.each do |family_user|
        %tr
          %td
            = users_avatar_img(family_user.user.decorate)
            = family_user.user.decorate.name
          %td= family_user.user.completed_homeworks_count
          %td= family_user.user.completed_homeworks_on_time_count
          %td= family_user.user.overdue_homeworks_count
          %td= family_user.user.average_rating
          %td
            - if policy(@family).edit_user?(family_user.user)
              = link_to t('general.edit'), edit_family_user_path(@family, family_user.user)
              \|
            - if policy(family_user).edit?
              = link_to t('.edit_role'), edit_family_family_user_path(@family, family_user)
              \|
            - if policy(family_user).destroy?
              = link_to t('.delete'), family_family_user_path(@family, family_user),
                method: :delete, 'data-confirm': t('general.confirm')

- if policy(@family).create_family_user? && famy_user_users_options(@family).any?
  = link_to t('.new'), new_family_family_user_path(@family)
  \|

- if policy(@family).edit?
  = link_to t('general.edit'), edit_family_path(@family)
  \|
= link_to t('general.back'), families_path