config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :families do
    resources :family_users, except: :index
    resources :categories, except: :index
    resources :users, only: %i[edit update]
    resources :homeworks do
      resources :user_homeworks, except: %i[index new]
    end
    get 'homeworks/:id/move_to_opened',
      to: 'homeworks#move_to_opened',
      as: :homework_move_to_opened
  end

  resources :user_homeworks, only: :index do
    resources :estimates,
      only: %i[new create],
      controller: :user_homework_estimates
    get 'estimate_consider', to: 'user_homework_estimates#consider'
    post 'estimate_decision', to: 'user_homework_estimates#decision'
    resources :requests,
      only: %i[new create],
      controller: :user_homework_requests
    resources :request_end,
      only: %i[new create],
      controller: :user_homework_request_ends
    resources :request_answer,
      only: %i[new create],
      controller: :user_homework_request_answers
    resources :request_answer_to_end,
      only: %i[new create],
      controller: :user_homework_request_answer_to_ends
  end

  resources :user_homeworks, only: [] do
    resources :ratings, only: %i[create update destroy]
  end

  resources :homeworks, only: [] do
    resources :comments, only: %i[new create] do
      resources :comments, only: :create
    end
  end

  root to: 'families#index'
end

app/controllers/user_homework_estimates_controller.rb
class UserHomeworkEstimatesController < ApplicationController
  include UserHomeworksResource
  include Estimateble

  before_action :authorize_homework_to_estimate, only: %i[new create]
  before_action :authorize_homework_to_approve_estimate,
    only: %i[consider decision]
  before_action :set_family
  before_action :find_comment, only: %i[consider decision]
  before_action :set_new_estimate_to_user_homework, only: :create

  def create
    if params[:comment] && @user_homework.save
      comment = create_comment(@homework)
      EstimateWasGivenNotificationsJob
        .perform_later(@user_homework, comment.id)
      redirect_to family_homeworks_path(@family)
    else
      render :new
    end
  end

  def decision
    render :consider unless params[:comment] || params[:aproved]

    comment = create_comment(@comment)
    if params[:aproved] == 'yes'
      @homework.start!
      EstimateAprovedNotificationsJob.perform_later @user_homework, comment
    else
      @homework.user_homework.clear_estimate
      EstimateRejectedNotificationsJob.perform_later @user_homework, comment
    end

    redirect_to family_homeworks_path(@family)
  end

  private

  def user_homework_params
    params.require(:user_homework).permit(:estimate)
  end

  def authorize_homework_to_estimate
    authorize @homework, :estimate?
  end

  def authorize_homework_to_approve_estimate
    authorize @homework, :approve_estimate?
  end
end

app/views/user_homework_estimates/_decision_form.html.haml
= simple_form_for(@user_homework,
  url: user_homework_estimate_decision_path(@user_homework, comment_id: @comment.id),
  method: :post) do |f|
  .form-group
    = radio_button_tag :aproved, 'yes', true
    = label_tag :aproved_yes, t('.aprove')
    %br
    = radio_button_tag :aproved, 'no'
    = label_tag :aproved_no, t('.reject')
  .form-group
    = hidden_field_tag 'comment_id', @comment.id
    = f.label :comment, required: true, for: 'comment'
    = text_area_tag 'comment', nil,
      placeholder: t('.comment'),
      class: 'form-control text',
      requited: true
  .form-group
    = f.submit

app/views/user_homework_estimates/_estimate_form.html.haml
= simple_form_for(@user_homework, url: user_homework_estimates_path(@user_homework), method: :post) do |f|
  .form-group
    = f.label :estimate, required: true
    .input-group.estimate-datetimepicker
      = f.input :estimate, as: :string, label: false, wrapper: false, required: true
      %span.input-group-addon
        %span.glyphicon.glyphicon-calendar
  .form-group
    = f.label :comment, required: true, for: :comment
    = text_area_tag :comment, nil,
      placeholder: t('.comment'),
      class: 'form-control text',
      requited: true
  .form-group
    = f.submit

app/views/user_homework_estimates/consider.html.haml
.page-header
  %h1= t('.title')

= render 'homeworks/homework'
= render 'decision_form'

= link_to t('general.back'), family_homeworks_path(@family)

app/views/user_homework_estimates/new.html.haml
.page-header
  %h1= t('.title')

= render 'homeworks/homework'
= render 'estimate_form'

= link_to t('general.back'), family_homeworks_path(@family)