config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :families do
    resources :family_users, except: :index
    resources :categories, except: :index
    resources :users, only: %i[edit update]
    resources :homeworks do
      resources :user_homeworks, except: %i[index new]
    end
    get 'homeworks/:id/move_to_opened',
      to: 'homeworks#move_to_opened',
      as: :homework_move_to_opened
  end

  resources :user_homeworks, only: :index do
    resources :estimates,
      only: %i[new create],
      controller: :user_homework_estimates
    get 'estimate_consider', to: 'user_homework_estimates#consider'
    post 'estimate_decision', to: 'user_homework_estimates#decision'
    resources :requests,
      only: %i[new create],
      controller: :user_homework_requests
    resources :request_end,
      only: %i[new create],
      controller: :user_homework_request_ends
    resources :request_answer,
      only: %i[new create],
      controller: :user_homework_request_answers
    resources :request_answer_to_end,
      only: %i[new create],
      controller: :user_homework_request_answer_to_ends
  end

  resources :user_homeworks, only: [] do
    resources :ratings, only: %i[create update destroy]
  end

  resources :homeworks, only: [] do
    resources :comments, only: %i[new create] do
      resources :comments, only: :create
    end
  end

  root to: 'families#index'
end

app/views/layouts/partials/_head.html.haml
%meta{'http-equiv': 'Content-Type', content: 'text/html; charset=utf-8'}
%title= content_for?(:title) ? yield(:title) : t('general.site_name')
= csrf_meta_tags
= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

app/views/layouts/partials/_header.html.haml
%nav.navbar.navbar-toggleable-md.navbar-inverse.bg-inverse.fixed-top
  .container-fluid
    .navbar-header
      = link_to t('general.site_name'), root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        - if current_user.nil?
          %li
            = link_to t('.login'), new_user_session_path
        - else
          %li.avatar
            = users_avatar_img(current_user)
          %li.dropdown
            .menu-icon.dropdown-toggle{'aria-expanded': false, 'aria-haspopup': true, 'data-toggle': :dropdown, type: :button}
              .glyphicon.glyphicon-th-list
            %ul.dropdown-menu
              %li
                = link_to t('header.menu.homeworks'), user_homeworks_path
              %li
                = link_to t('header.menu.settings'), edit_user_registration_path
              %li.divider{role: :separator}
              %li
                = link_to t('header.menu.logout'), destroy_user_session_path